# Generated by Django 6.0.6 on 2026-06-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mijoz/Kompaniya nomi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('address', models.TextField(verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ombordagi qoldiq (dona)')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor (dona)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name="Umumiy summa (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='water.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Fakturalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
