# Generated by Django 6.0.6 on 2026-06-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_product_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name="Umumiy summa (so'm)"),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor (dona)')),
                ('item_total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name="Satr summasi (so'm)")),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='water.invoice', verbose_name='Faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Faktura mahsuloti',
                'verbose_name_plural': 'Faktura mahsulotlari',
            },
        ),
    ]
